# Generated by Django 5.2.4 on 2025-07-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('main', 'غذاهای اصلی'), ('dessert', 'دسرها'), ('appetizer', 'پیش غذا'), ('drink', 'نوشیدنی\u200cها'), ('soup', 'سوپ و آش'), ('salad', 'سالاد')], max_length=50, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('display_name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دستور پخت')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('description', models.TextField(max_length=500, verbose_name='توضیح کوتاه')),
                ('image', models.ImageField(upload_to='recipes/images/', verbose_name='تصویر اصلی')),
                ('prep_time', models.PositiveIntegerField(verbose_name='زمان آماده\u200cسازی (دقیقه)')),
                ('cook_time', models.PositiveIntegerField(verbose_name='زمان پخت (دقیقه)')),
                ('servings', models.PositiveIntegerField(verbose_name='تعداد نفرات')),
                ('calories_per_serving', models.PositiveIntegerField(verbose_name='کالری به ازای هر نفر')),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], max_length=10, verbose_name='سطح سختی')),
                ('instructions', models.TextField(verbose_name='طرز تهیه')),
                ('is_featured', models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دستور پخت',
                'verbose_name_plural': 'دستور پخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='کالری')),
                ('protein', models.FloatField(default=0, verbose_name='پروتئین (گرم)')),
                ('carbs', models.FloatField(default=0, verbose_name='کربوهیدرات (گرم)')),
                ('fat', models.FloatField(default=0, verbose_name='چربی (گرم)')),
                ('fiber', models.FloatField(default=0, verbose_name='فیبر (گرم)')),
                ('sugar', models.FloatField(default=0, verbose_name='قند (گرم)')),
                ('sodium', models.FloatField(default=0, verbose_name='سدیم (میلی\u200cگرم)')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='recipe.recipe', verbose_name='دستور پخت')),
            ],
            options={
                'verbose_name': 'اطلاعات تغذیه\u200cای',
                'verbose_name_plural': 'اطلاعات تغذیه\u200cای',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ماده اولیه')),
                ('amount', models.CharField(max_length=50, verbose_name='مقدار')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='واحد')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe', verbose_name='دستور پخت')),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'مواد اولیه',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(verbose_name='آی\u200cپی کاربر')),
                ('is_like', models.BooleanField(verbose_name='لایک است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='recipe.recipe', verbose_name='دستور پخت')),
            ],
            options={
                'verbose_name': 'امتیاز دستور پخت',
                'verbose_name_plural': 'امتیازات دستور پخت\u200cها',
                'unique_together': {('recipe', 'user_ip')},
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='شماره مرحله')),
                ('instruction', models.TextField(verbose_name='توضیحات مرحله')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/steps/', verbose_name='تصویر مرحله')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipe.recipe', verbose_name='دستور پخت')),
            ],
            options={
                'verbose_name': 'مرحله طرز تهیه',
                'verbose_name_plural': 'مراحل طرز تهیه',
                'ordering': ['step_number'],
                'unique_together': {('recipe', 'step_number')},
            },
        ),
    ]
